_wandb:
    value:
        cli_version: 0.23.0
        e:
            coo04zrc7cpui9evxfgk4u7rq2tgdvh8:
                args:
                    - --wandb-project
                    - my-rag
                    - --wandb-run
                    - mytest
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1000186310656"
                        used: "902198534144"
                email: dksksj12@gmail.com
                executable: F:\codeit_ai_rfp_rag_assistant\.venv\Scripts\python.exe
                git:
                    commit: 344c966038357644afc37c315753e54e8dcc8aa7
                    remote: https://github.com/cmustard7/codeit_ai_rfp_rag_assistant.git
                gpu: NVIDIA GeForce RTX 4070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7680
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 Ti
                      uuid: GPU-ae74a6c4-0b11-6001-0358-1b71e969f242
                host: DESKTOP-88AI8A6
                memory:
                    total: "51418107904"
                os: Windows-11-10.0.26100-SP0
                program: -m src.run_eval
                python: CPython 3.12.10
                root: F:\codeit_ai_rfp_rag_assistant
                startedAt: "2025-11-27T00:43:23.540509Z"
                writerId: coo04zrc7cpui9evxfgk4u7rq2tgdvh8
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 11
                - 49
                - 92
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
                - 92
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.12.10
            "5": 0.23.0
            "6": 4.57.1
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
CHUNK_OVERLAP:
    value: "300"
CHUNK_SIZE:
    value: "1400"
ENABLE_BM25:
    value: "1"
ENABLE_MMR:
    value: "1"
ENABLE_PARAPHRASE:
    value: "1"
ENABLE_RERANK:
    value: "1"
PARAPHRASE_N:
    value: "2"
RERANK_MODEL:
    value: BAAI/bge-reranker-v2-m3
RERANK_SCORE_FLOOR:
    value: "0.2"
question_count:
    value: 21
