_wandb:
    value:
        cli_version: 0.21.4
        e:
            vqs53b5tkizmmeazuvnb4jxoussemluy:
                args:
                    - --wandb-project
                    - my-rag
                    - --wandb-run
                    - hwp2hwpx
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1000186310656"
                        used: "901407035392"
                email: dksksj12@gmail.com
                executable: C:\Users\my\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 344c966038357644afc37c315753e54e8dcc8aa7
                    remote: https://github.com/cmustard7/codeit_ai_rfp_rag_assistant.git
                gpu: NVIDIA GeForce RTX 4070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7680
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 Ti
                      uuid: GPU-ae74a6c4-0b11-6001-0358-1b71e969f242
                host: DESKTOP-88AI8A6
                memory:
                    total: "51418107904"
                os: Windows-10-10.0.26100-SP0
                program: -m src.run_eval
                python: CPython 3.10.9
                root: F:\codeit_ai_rfp_rag_assistant
                startedAt: "2025-11-26T07:09:50.406517Z"
                writerId: vqs53b5tkizmmeazuvnb4jxoussemluy
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 92
                - 95
                - 105
            "2":
                - 1
                - 11
                - 49
                - 92
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.9
            "5": 0.21.4
            "6": 4.57.1
            "8":
                - 3
            "12": 0.21.4
            "13": windows-amd64
question_count:
    value: 26
